HISTORY_INDEX_REFRESH_INTERVAL=60
CLAMAV_SLEEP_TIMER=3600
WEB_FIRSTRUN_COMPLETED=0
WEB_LOGIN_MAX_TRIES=10
WEB_LOGIN_MAX_TRIES_OVERALL=100
WEB_LOGIN_COOLDOWN_INTERVAL=600
SERVER_TRUSTED_REVERSEPROXY=
LOG_FILE_MAX_SIZE=5242880
LOG_FILE_NUM=5
LOG_LEVEL=warn
